### ISSUE TITLE
downsampling

### ISSUE THREAD

**Issue by liamxg** [grubaughlab/2023_paper_DENV-travelers#1]
Dear @ViralVerity,
In your manuscript:
"We used all sequences sampled from the Caribbean and then took up to 10 sequences per country or territory per year per serotype, with a strict coverage cut-off applied to all sequences of 70%. "

Could you please tell me how to do this, thanks.

**Comment by ViralVerity** [comment]
We did the coverage cut-off in the downloading process (you can do this on NCBI virus) and used a custom script to do 10 sequences per country per year per serotype - you can do that in R or Python fairly easily

**Comment by liamxg** [comment]
Dear @ViralVerity,

Could you please share your custom script, thanks.
