### ISSUE TITLE
where to find the "../introductions_analysis/{sero}_whole_caribbean.csv" file?

### ISSUE THREAD

**Issue by liamxg** [grubaughlab/2023_paper_DENV-travelers#2]
Dear @ViralVerity,

Could you please tell me where to find the "../introductions_analysis/{sero}_whole_caribbean.csv" file? 

Hope you can reply to me, thanks.

**Comment by ViralVerity** [comment]
That is a file that gets produced by the "parse introductions" script - I've tidied up that script a bit so it should be easier to use (ie I've removed my local paths)

**Comment by liamxg** [comment]
Dear @ViralVerity,

Could you please upload the all input files for run `Parse introductions.ipynb`, thanks.

**Comment by ViralVerity** [comment]
You can generate the trees file required by running the XML in the XMLs folder

**Comment by liamxg** [comment]
Hi @ViralVerity,
I am very interested about this project, this is a amazing!
However, even I run the xml files, they are still many `*csv` files that I do not know where to get, and what is the output will be?

Is there any issue to upload them?

**Comment by ViralVerity** [comment]
Both CSVs in the "parse introductions" script are generated by the script! It takes a MCC tree from the discrete phylogeography as its input

**Comment by liamxg** [comment]
Thanks. I am much clear now. 

Great project.

**Comment by liamxg** [comment]
BTW, you use this version of BEAST?

<img width="1023" alt="image" src="https://github.com/grubaughlab/2023_paper_DENV-travelers/assets/46078579/06dcab4e-dcf4-4c99-8fd7-002d3064ac81">

**Comment by ViralVerity** [comment]
Yes I think so - it doesn't really make a difference for this analysis though

**Comment by liamxg** [comment]
okay, cool!

**Comment by liamxg** [comment]
Hi, please see below:

<img width="1202" alt="image" src="https://github.com/grubaughlab/2023_paper_DENV-travelers/assets/46078579/eeb5f980-a30d-4516-9acc-7cd4305ab50a">
